from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ------------------------------------------------------------------------------

env = environ.Env()

environ.Env.read_env(BASE_DIR / '..' / 'secrets' / '.env')

RNV = env('RNV', default='prod')

if RNV == 'dev':
    DEBUG = True
    DATABASES = { 'default': env.db_url('DJANGO_DB_URL_DEV',) }
    STATIC_URL = '/static/'  # 'static/'
    ALLOWED_HOSTS = ['127.0.0.1']
    ENV_NAME = 'Devel (Local)'
    ADMIN_HEADER_BG = '#089c2f'  # green
elif RNV == 'prod':
    DEBUG = False  # SECURITY WARNING: don't run with debug turned on in production!
    DATABASES = { 'default': env.db_url('DJANGO_DB_URL',) }
    STATIC_URL = env('DJANGO_STATIC_URL')
    ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS')
    CSRF_TRUSTED_ORIGINS = env.list('DJANGO_CSRF_TRUSTED_ORIGINS')
    ENV_NAME = '*** PRODUCTION ***'
    ADMIN_HEADER_BG = '#961313'  # red

# ------------------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

ADMIN_URL = env('DJANGO_ADMIN_URL')

STATIC_ROOT = env('DJANGO_STATIC_ROOT')

PROJECT_NAME = env('DJANGO_PROJECT_NAME')  # , default = None

# ANA_GA4_ID = env('ANA_GA4_ID', default = None)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # custom user model
    'dpa_aux_users',
]

AUTH_USER_MODEL = 'dpa_aux_users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls_root'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'django_project' / 'templates',
            BASE_DIR / 'django_project_reuse' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'django_project_reuse.context.reuse',
            ],
        },
    },
]


# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/dev/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ------------------------------------------------------------------------------

'''
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.1a1.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
'''

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# WSGI_APPLICATION = 'django_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/